export const movieConstants = {
  SHOWS_REQUEST: "SHOWS_REQUEST",
  SHOWS_SUCCESS: "SHOWS_SUCCESS",
  SHOWS_FAILURE: "SHOWS_FAILURE",

  SHOW_REQUEST: "SHOW_REQUEST",
  SHOW_SUCCESS: "SHOW_SUCCESS",
  SHOW_FAILURE: "SHOW_FAILURE",

  MOVIES_REQUEST: "MOVIES_REQUEST",
  MOVIES_SUCCESS: "MOVIES_SUCCESS",
  MOVIES_FAILURE: "MOVIES_FAILURE",

  MOVIE_REQUEST: "MOVIE_REQUEST",
  MOVIE_SUCCESS: "MOVIE_SUCCESS",
  MOVIE_FAILURE: "MOVIE_FAILURE",

  SEARCHSHOWS_REQUEST: "SEARCH_SHOWS_REQUEST",
  SEARCHSHOWS_SUCCESS: "SEARCH_SHOWS_SUCCESS",
  SEARCHSHOWS_FAILURE: "SEARCH_SHOWS_FAILURE",

  SEARCHMOVIES_REQUEST: "SEARCH_MOVIES_REQUEST",
  SEARCHMOVIES_SUCCESS: "SEARCH_MOVIES_SUCCESS",
  SEARCHMOVIES_FAILURE: "SEARCH_MOVIES_FAILURE"
};
